# Generated by Django 4.2.23 on 2025-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_messagingserviceconfig_last_failure_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingserviceconfig',
            name='kind',
            field=models.CharField(choices=[('slack', 'Slack (or compatible)'), ('discord', 'Discord')], default='slack', max_length=20),
        ),
    ]
